name    'akandels-phpunit'
version '1.0.0'
source 'UNKNOWN'
author 'akandels'
license 'BSD License, Version 2.0'
summary 'Installs the PHPUnit PHAR package to an executable path for running unit tests for your PHP-based applications.'
description 'Installs the PHPUnit PHAR package to an executable path for running unit tests for your PHP-based applications.'
project_page 'https://github.com/andrew-kandels/puppet-phpunit'
dependency 'maestrodev/wget', '>= 1.4.1'
